### ISSUE TITLE
Unable to save datacube due to h5py/string interaction

### ISSUE THREAD

**Issue by tcpekin** [py4dstem/py4DSTEM#108]
I am trying to save a file using the following command: `    save(data, data_path[:-3] + '_bksbtr.h5', overwrite=True)
`, where save has been previously imported from py4DSTEM. However, I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/Research/Data/2020/in_situ_heating_experiment/in_situ_heating_analysis.py in <module>
     41 
     42     # temporary save
---> 43     py4DSTEM.file.io.write.save(data, data_path[:-3] + '_bksbtr.h5')
     44 
     45 # characterize mean diffraction pattern ellipticity

~/Documents/Research/code/py4DSTEM/py4DSTEM/file/io/write.py in save(data, outputfile, **kwargs)
    204     """
    205     if isinstance(data, DataObject):
--> 206         save_dataobject(data, outputfile, **kwargs)
    207     elif isinstance(data, int):
    208         save_dataobjects_by_indices([data], outputfile, **kwargs)

~/Documents/Research/code/py4DSTEM/py4DSTEM/file/io/write.py in save_dataobject(dataobject, outputfile, **kwargs)
    177 
    178     # Save
--> 179     save_from_dataobject_list([dataobject], outputfile, **kwargs)
    180 
    181 #@log

~/Documents/Research/code/py4DSTEM/py4DSTEM/file/log.py in logged_function(*args, **kwargs)
    106                                  datetime = localtime())
    107 
--> 108         return function(*args,**kwargs)
    109 
    110     return logged_function

~/Documents/Research/code/py4DSTEM/py4DSTEM/file/io/write.py in save_from_dataobject_list(dataobject_list, outputfile, topgroup, overwrite, **kwargs)
    163     group_log = group_toplevel.create_group("log")
    164     for index in range(logger.log_index):
--> 165         write_log_item(group_log, index, logger.logged_items[index])
    166 
    167     ##### Finish and close #####

~/Documents/Research/code/py4DSTEM/py4DSTEM/file/io/write.py in write_log_item(group_log, index, logged_item)
    610             except TypeError:
    611                 group_inputs.attrs.create(key, np.string_(str(value)))
--> 612     group_logitem.attrs.create('version', logged_item.version)
    613     write_time_to_log_item(group_logitem, logged_item.datetime)
    614 

~/miniconda3/envs/hyperspy/lib/python3.6/site-packages/h5py/_hl/attrs.py in create(self, name, data, shape, dtype)
    169             # Make HDF5 datatype and dataspace for the H5A calls
    170             if use_htype is None:
--> 171                 htype = h5t.py_create(original_dtype, logical=True)
    172                 htype2 = h5t.py_create(original_dtype)  # Must be bit-for-bit representation rather than logical
    173             else:

h5py/h5t.pyx in h5py.h5t.py_create()

h5py/h5t.pyx in h5py.h5t.py_create()

h5py/h5t.pyx in h5py.h5t.py_create()

TypeError: No conversion path for dtype: dtype('<U5')

```

I looked into this a little bit, and it seems to be something with using strings as tags, or attributes in h5py, and not integers, but I'm not sure how to begin fixing this...

**Comment by ercius** [comment]
You need to be careful when using strings with hdf5 and h5py. You can read about how h5py deals with [python strings in this article](http://docs.h5py.org/en/stable/strings.html).

However, this might not be the issue here. The [dtype string](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) in the error indicates you are trying to use a Unicode string (U) with 5 bytes. Never heard of that before! 

If its a unicode string then it [gets pretty complicated](https://docs.python.org/3/howto/unicode.html). Your data_path might have some weird string type. Maybe it has some non-English character(s) in it? Try `data_path.encode('UTF-8').decode('ascii')` to convert it. If you get an error then there is a unicode character in there that cant be converted.

You can also have a look at python's `pathlib.Path` as an easier way to manipulate file paths and it is cross-platform. For example you can do this to replace your path manipulation:
```python
from pathlib import Path
data_path = Path(data_path)
save_path = data_path.with_name(data_path.stem + '_bksbtr').with_suffix('.h5')
save(data, str(save_path), overwrite=True)
```
Im not sure if py4DSTEM works with pathlib.Path which is why you need the `str()` to turn the path into a string in `save`.

**Comment by tcpekin** [comment]
Thanks for the info Peter, I looked into it a bit more, trying to save just some sort of test datacube with a very simple filename (using both the decode encode string methods, and the str(Path(...)) approach), as well as path names that were just something like 'test.h5', and the same error occurred every time. I think it might have to do with some string the logging functions are outputting?

**Comment by sezelt** [comment]
Yeah it has to be in the logging functions because by the time you get to line 165 in write.py the file has already been created.

Could you put a breakpoint/use the debugger to see what the value & dtype of `logged_item.version` is at `write.py:612` (the second-to-last call on the trace)? I suspect that somehow that is the problem. Best I can tell this should always contain the value in the global `__version__`, which should be `0.7 (float)`, which should be OK as an HDF5 attribute.  

For a quick workaround you can just comment out `@log` anywhere it appears in py4DSTEM

**Comment by tcpekin** [comment]
Ok in  the `write_log` function, `logged_item.version` is a _string_, `0.8.0`. So I guess that needs to be changed? Where is that originally set?

**Comment by tcpekin** [comment]
I also see where it comes from, version.py, and how it used to be a float in the git history, and is now a string to support sub-versioning. I guess now the question is how do we deal with saving strings in hdf5, which is what Peter was talking about earlier.

**Comment by tcpekin** [comment]
Changing version to a float in version.py fixes all problems, and I'll do that locally until @sezelt or @bsavitzky has a more permanent solution.

**Comment by bsavitzky** [comment]
Thanks guys, sorry I've been MIA on this - I changed the versioning scheme
and made this a string. Glad this will work for now, soon I can update the
logging so that it handles the strings for HDF5.
