### ISSUE TITLE
Ideal cross correlation kernel

### ISSUE THREAD

**Issue by rohandhall** [py4dstem/py4DSTEM#16]
Hey Ben/Steven,

Playing around with py4Dstem, I find the most time consuming part is finding good parameters for the probe radius and width.  Especially if camera length changes, current method of evaluating a good probe is not robust. 

I am having better luck with simple thresholding algorithms. Maybe something to try, would be to record probes under different experimental conditions (convergence angle, camera length), and convert them to "r,w" values. Once you have this table you can hopefully interpolate for ideal probe parameters. 

Another approach might be to bandpass filter the diffractionslices to try and highlight the bragg peaks.  

Also-- am I the only one having this issue because I'm dumb, or is this something that you also encounter regularly?

**Comment by rohandhall** [comment]
Hey,

So turns out I am dumb (always a good assumption). After more digging around, I find the cross correlation kernel doesnt really matter, which makes sense (considering how good simple threholding was working on this data). 

Instead,  the function find_Bragg_disks_DP_FK has a bad value set for the minPeakSpacing parameter (for my dataset). The default is 60 pixels, which was making my data look dumb. 

My fault. I will close issue. 

Cheers

**Comment by sezelt** [comment]
Rohan,
I feel like the questions you raised do actually touch on some stuff that we don’t have 100% figured out so this may be a worthwhile discussion.
First, which parameters do you mean by probe radius and width? Are you generating a probe using `get_average_probe_from_vacuum_scan(...)`, `get_average_probe_from_ROI(...)` or `get_synthetic_probe(...)`? The first two are relatively insensitive to the parameters in my experience, and the parameters usually (in my experience) scale directly with the probe radius (Ben-perhaps we should note some rules of thumb for these if we can work them out with some confidence..?) The last option (synthetic probe) is definitely really sensitive to the parameters and imo should be used only if you absolutely positively cannot generate a probe from the data cube. 

Also, are you using the Gaussian subtraction of the probe? This has, in my experience, caused some weirdness at higher convergence angles...

Finally, Ben– What do you think about having (perhaps by default) the `find_Bragg_disks` functions use the probe radius (or some function thereof) as the minimum peak spacing? I feel like throwing away only disks that are less than a probe diameter away is the least restrictive condition; it throws away peaks that are almost certainly due to multiple identifications of the same true Bragg disk; and best allows for the detection of weak peaks like from superlattice reflections that people might inadvertently throw away if they tune parameters by finding the *highest* threshold that doesn’t throw away strong reflections...

Also also, random thought, a nice thing to have would be (for datasets that have the metadata set) for stuff like the estimated probe size to be converted to mrad (like in the output of the functions that find the kernel) as a sanity check...
