### ISSUE TITLE
`tqdmnd` moved?

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#433]
Is there a reason that `tqdmnd` is now imported from `emdfile` rather than from `py4DSTEM`?
https://github.com/py4dstem/py4DSTEM/blob/7e05ac15c8e48b823f01af85e717bc765ded0a2b/py4DSTEM/__init__.py#L42
It's rather confusing since `tqdmnd` still exists in py4DSTEM (py4DSTEM/utils/tqdmnd.py), but it seems that even at the module level we import it from `emdfile`. 
This is also causing a circular import in #430 for some reason, probably related to the order of initialization of different submodules. 

What do we think about making `tqdmnd` a separate lightweight package? It definitely has some general utility. Right now it only exists independently as a gist, and then in multiple copies in different repos.

**Comment by bsavitzky** [comment]
Hey Steve - I moved it to emdfile because we use it when loading PointListArrays, and thought it would be ok to just import from emdfile, since we import everything from there anyway.  The redundant copy in py4DSTEM.utils should definitely be removed.  I would suggest just taking that out and using the import from emdfile, rather than having a whole package just for this one function - emdfile is already quite lightweight, and this will be easier to do and also easier to maintain.  What do you think?

**Comment by sezelt** [comment]
see #436
