### ISSUE TITLE
runGUI.py segmentation fault due to multiple incompatible subclass instances

### ISSUE THREAD

**Issue by zezhong-zhang** [py4dstem/py4DSTEM#45]
Hi Colin and Hamish, 

I had a quick install of the code and currently, I run into a crashing bug with GUI. It reports as segmentation fault in the terminal and I had a look of the python traceback as follow. 

The system is on Mac OS with clean conda environment python=3.7 following the instruction.
Cheers,
Zezhong

---------------------------------------------------------------------------
MultipleInstanceError                     Traceback (most recent call last)
<ipython-input-7-18f179a8b3db> in <module>
      2 
      3 if __name__ == '__main__':
----> 4     app = py4DSTEM.gui.DataViewer(sys.argv)
      5 
      6     sys.exit(app.exec_())

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/py4DSTEM-0.4-py3.7.egg/py4DSTEM/gui/viewer.py in __init__(self, argv)

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/py4DSTEM-0.4-py3.7.egg/py4DSTEM/gui/viewer.py in setup_console_widget(self)

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/ipykernel/inprocess/manager.py in start_kernel(self, **kwds)
     44     def start_kernel(self, **kwds):
     45         from ipykernel.inprocess.ipkernel import InProcessKernel
---> 46         self.kernel = InProcessKernel(parent=self, session=self.session)
     47 
     48     def shutdown_kernel(self):

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/ipykernel/inprocess/ipkernel.py in __init__(self, **traits)
     70 
     71     def __init__(self, **traits):
---> 72         super(InProcessKernel, self).__init__(**traits)
     73 
     74         self._underlying_iopub_socket.observe(self._io_dispatch, names=['message_sent'])

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/ipykernel/ipkernel.py in __init__(self, **kwargs)
     65             user_module = self.user_module,
     66             user_ns     = self.user_ns,
---> 67             kernel      = self,
     68         )
     69         self.shell.displayhook.session = self.session

~/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/traitlets/config/configurable.py in instance(cls, *args, **kwargs)
    421             raise MultipleInstanceError(
    422                 'Multiple incompatible subclass instances of '
--> 423                 '%s are being created.' % cls.__name__
    424             )
    425 

MultipleInstanceError: Multiple incompatible subclass instances of InProcessInteractiveShell are being created.

**Comment by HamishGBrown** [comment]
Hi Zhezhong,

Good to hear from you and hope that the new postdoc in Antwerp is going well. I can reproduce your error on my Linux machine but only if I try to launch the GUI by typing the command `ipython runGUI.py` in the terminal, if I type `python runGUI.py` it works. Can you try using python instead of ipython?

@bsavitzky eventually we might want to understand this anomaly, but for the time being should we explicitly mention to not use ipython in the readme.md[https://github.com/py4dstem/py4DSTEM#running-py4dstem-with-the-gui]?

**Comment by zezhong-zhang** [comment]
`python runGUI.py`
> [2]    13747 segmentation fault python runGUI.py

I only tried python in the terminal and it yields segmentation fault. The traceback of the subclass instances is extracted from the jupyter notebook if I run the script embedded in the runGUI.py.

**Comment by bsavitzky** [comment]
Hi Zezhong,

I'm not sure I'm clear on exactly the issue you're having - in particular, you mention a jupyter notebook above: are you trying to launch the runGUI.py script from a jupyter notebook?  If so that is likely the problem - this script needs to be launched from the command line and not from jupyter.  So on your mac, you'll want to open a terminal, navigate to the directory containing the runGUI.py script, and type

```
python runGUI.py
```

Does this help / have I understood the situation correctly?

Cheers,
Ben

**Comment by zezhong-zhang** [comment]
Now GUI using `py4dstem` works perfectly well in version 0.12.6 when I tried today, hence I close this issue (sorry for the delay).
