### ISSUE TITLE
error during ptychography reconstruction in gpu mode

### ISSUE THREAD

**Issue by yongsooyang** [py4dstem/py4DSTEM#583]
**Describe the bug**
I found errors in four different occasions:

1) attributeerror: module 'cupy' has no attribute 'round'
This happened when I first run the following line:

ptycho = py4DSTEM.process.phase.SingleslicePtychographicReconstruction(
datacube=dataset_pad,
verbose=True,
energy=300e3,
semiangle_cutoff=30,
defocus=0,
device='gpu',
).preprocess(
plot_center_of_mass = False,
plot_rotation = False,
force_com_rotation = np.rad2deg(dpc._rotation_best_rad) + 180.0,
force_com_transpose = False,
plot_probe_overlaps = True,
)

To fix the problem, I changed every "xp.round" to "xp.around" for all the cases I found in 
iterative_multislice_ptychography.py, iterative_base_class.py, and iterative_singleslice_ptychography.py,
then it seems to be working (I actually don't know if it is working correctly or not. It just does not produce errors anymore after this modification).

2)  catastrophic error: cannot open source file "math_constants.h
This problem seems to be related to cupy, not py4dstem. I am unsure if this is a right place to put info about this, but I encountered this problem during py4DSTEM function call, so I am putting this info here just in case this would help someone having the same issue while running py4DSTEM.

It seemed that this problem happened because the "CUDA_PATH" environment variable did not have the path for the "math_constants.h" header file in my Windows machine.
Running the following line in the anaconda prompt before launching the python kernel resolved the issue in my case (the actual location of the header file directory will most likely be different for other machines):

set CUDA_PATH=%CUDA_PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include

3) AttributeError: 'cupy.cuda.memory.MemoryPointer' object has no attribute 'ndim'
This happened when I first run the following line:

py4DSTEM.show([
np.fft.fftshift(np.abs(np.fft.fft2(ptycho._probe))),
dataset_pad.get_dp_mean()
])

I attached a screenshot for this error.

4) IndexError: tuple index out of range
This happened when I first run the following line:

ptycho = ptycho.reconstruct(
reset=True,
progress_bar = True,
store_iterations = True,
max_iter = 16,
pure_phase_object_iter = 4,
step_size = 0.9,
normalization_min = 0.2,
gaussian_filter_sigma = 0.75,
).visualize(
iterations_grid='auto',
)

I checked this for "ptycho" object prepared with both SingleslicePtychographicReconstruction and MultislicePtychographicReconstruction , and both cases produce the same error.

**To Reproduce**
Just running the example jupyter notebook for ptychography in gpu mode will reproduce it, I guess.

**Expected behavior**
Successful (miltislice) pytchography reconstruction

**py4DSTEM version** 
'0.14.8'
**Python version**
Python 3.9.18
**Operating system** 
Windows 11

**GPU**
If GPU related please provide:
- CUDA driver - 545.84 CUDA 12.3
- Cupy Version - '8.3.0'

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

![cupy_ndim_error](https://github.com/py4dstem/py4DSTEM/assets/24594416/a52c5a40-c2c1-41c6-9161-aaa3a68bde19)
![singleptycho_reconstruct_error](https://github.com/py4dstem/py4DSTEM/assets/24594416/aaa6d62a-4beb-492c-9af7-c84d6852bf60)
![cupy_ndim_error](https://github.com/py4dstem/py4DSTEM/assets/24594416/d8bb72f0-ff18-4294-a249-b1a0ba0ad638)
![singleptycho_reconstruct_error](https://github.com/py4dstem/py4DSTEM/assets/24594416/8f020095-2dce-407a-b6d7-2bea2d8c3d62)

**Additional context**
Please feel free to add any other context about the problem here.

**Comment by yongsooyang** [comment]
Hey @gvarnavi,

Thanks for the comment. Upgrading to cupy 10.2 indeed solved the last bug, but the third problem related to py4DSTEM.show still exits. It would be great if you could help regarding this issue when you have time. Thanks a lot!

**Comment by gvarnavi** [comment]
Hey @yongsooyang,

Apologies -- I hadn't read the third issue carefully the first time. This is in-fact very simple to fix by using `ptycho.probe` instead of `ptycho._probe`.  

If you're curious about the seemingly duplicate variables, read on:  
Essentially, we currently use the `xp=np/cp` pattern to enable single-node GPU acceleration using cupy as a drop-in replacement for numpy. Since our workflow is meant to be chained (e.g. `ptycho.preprocess().reconstruct()`), we try to avoid sending arrays back and forth the GPU/CPU by keeping all the arrays on the device.  

As such, the "private" attributes which start with an underscore (e.g. `ptycho._probe`*, `ptycho._object`) will always be stored on the GPU if `device="gpu"`. By contrast, the "public-facing" attributes w/o a leading underscore (e.g. `ptycho.probe`, `ptycho.object` etc) return a copy of the array on the CPU (which is what matplotlib requires for plotting). Note that you can also use the `ptycho._asnumpy(ptycho._object)` function to copy any GPU array on demand.

Finally, note that we're planning an overhaul of the GPU acceleration (presumably sometime over winter break) to support streaming to the GPU for calculations, but storing all the arrays on the CPU, which should make this significantly less convoluted.

Closing this issue, but feel free to re-open if any GPU-issues persist. 

\* PS: For the probe specifically, note that internally we store them as corner-centered to avoid using fftshift, so `ptycho.probe` is in-fact `ptycho._asnumpy(ptycho._return_centered_probe(ptycho._probe))` to return a centered-probe for plotting.
