### ISSUE TITLE
Ptychography gridding pattern

### ISSUE THREAD

**Issue by erh3cq** [py4dstem/py4DSTEM#644]
**Problem:**
Ptychography reconstruction on Dectris (and other hybrid detectors with segments) is creating a 'gridding pattern' upon reconstruction. The grid can be seen in real and reciprocal space, but is most obvious in reciprocal space.
![qbin2ptycho_-_reconstruction_obj_phase_720](https://github.com/py4dstem/py4DSTEM/assets/25358789/54998009-6b1b-4d8b-9642-3e284fbaeaee)
![qbin2ptycho_-_reconstruction_fft_720](https://github.com/py4dstem/py4DSTEM/assets/25358789/2a9d9045-e19d-426c-b3ad-a0d5bc9a5611)

**Trouble shooting:**
1. The periodicity matches the probe step size. I have run acquisitions with various combinations of max outer angle, binning, and probe step size.
![qbin2ptycho_-_reconstruction_fft_720](https://github.com/py4dstem/py4DSTEM/assets/25358789/7c1b699f-edf3-48ac-99f8-48ad48acd429)
![ptycho_-_reconstruction_fft_720](https://github.com/py4dstem/py4DSTEM/assets/25358789/61bc2873-cb3d-4e25-b678-3f59b36ce10b)
2. @smribet rean Bayesian Optimization of position, aberrations, and mixed state. This helped to some minor degree but the issue is still prominent.
![240223_eric_object_fft_360](https://github.com/py4dstem/py4DSTEM/assets/25358789/ebc4c0da-cc8c-4c39-bfa5-40d48ea33343)
3. I ran the "ptycho01_gold_on_carbon.ipynb" file then ran it again with simulated boarder pixels by averaging (e.g. each boarder pixel is a 2x1 pixel that is then assigned to two 1x1 pixels with each having the same intensity). The artifact did not appear. This would suggest it is not 
![Figure 48](https://github.com/py4dstem/py4DSTEM/assets/25358789/2102222e-13d5-4c55-afbd-f0fef858eb24)
the averaging of the boarder pixels that creates the issue.
![Figure 49](https://github.com/py4dstem/py4DSTEM/assets/25358789/7eaf56ef-0492-48da-ae50-210d173673ee)

**Expected behavior:**
artifact free reconstruction

**Things to try**
@cophus suggested a series of filter that @smribet or @gvarnavi could implement

**py4DSTEM version** 
0.14.9 (from github phase)
**Python version**
3.12.1
**Operating system** 
Windows

**Comment by tcpekin** [comment]
I saw extremely similar grid artifacts using a Dectris when either the pixel or step size was incorrect. The mitigation by updating probes and probe position kind of also hints at that... Idk could just be a me problem, but I am haunted by grid patterns that look like that 😂

**Comment by gvarnavi** [comment]
Thanks for the report @erh3cq!
I've been sitting on a tutorial notebook which investigates gridding-artifacts for the past couple of weeks, and haven't found time to finalize/post it. Attaching it here in the meantime, you can find the necessary data files [here](https://drive.google.com/drive/folders/1eKLEZn7aEM-1jq9N1N1X5yRmnbEslhji?usp=drive_link).

[iterative-ptychography_02.zip](https://github.com/py4dstem/py4DSTEM/files/14854747/iterative-ptychography_02.zip)

Unfortunately, gridding is a pathological artifact in "blind" ptychography (i.e. where one tries to solve for the probe and the object simultaneously). This is well-known in the X-Ray ptychography literature, and in-fact why they have switched away from raster-scans and instead opt for spiral scans.

That being said, the notebook investigates regimes where this is more/less pronounced - and possible remedies. I summarize them here briefly with this figure, but do have a look at the notebook:

![gridding-experiments](https://github.com/py4dstem/py4DSTEM/assets/19610677/d15df51c-d18d-4d7d-81ee-6711542929ca)

- Lower batch-sizes hide a lot of sins, and allow the probe (which is the first to absorb gridding, and then transfer it to the object) to update more frequently
  - "Dummy" mixed-state hides even more. You can use mixed-state with 2 probes and a large batch_size to essentially dump a lot of the probe artifacts into a sacrificial, low-intensity probe mode. This includes gridding, but it also absorbs the mean-diffraction pattern for free
![Screenshot from 2024-04-03 08-46-41](https://github.com/py4dstem/py4DSTEM/assets/19610677/9e40c60e-14f1-4de6-a95c-6f33e0eba35b)
- Gridding can be overcome with sufficient dataset redundancy, i.e. finer probe sampling
  - Note you don't want to achieve this using larger defocus, since you need a very comfortable cropping box to avoid self-interaction (the notebook suggests even 0.1% self-interaction results in aggressive gridding!)
- Vacuum probe measurements are great for initializing the probe, but if it's even slightly off from the measured intensities' BF-disk you probably don't want to be forcing it, as even slight model-mismatch results in gridding (note you might not have a choice for low-dose datasets)

Finally, you mention implementing a filter for this. Indeed - the gridding artifacts are predictable, and we can easily add a Fourier filter which zeros-out those pixels. You get what you ask for with Fourier-filtering, so indeed this can reduce/remove gridding but our tests have shown the reconstructions to be fairly sub-optimal in other ways.

**Comment by gvarnavi** [comment]
To clarify, and connect with @tcpekin comment above:
> I saw extremely similar grid artifacts using a Dectris when either the pixel or step size was incorrect

Gridding is a pathological artifact due to the translation periodicity ambiguity introduced by raster scan patterns, and can be exacerbated by ANY kind of model-mismatch. The notebook above investigates the probe aperture and cropping box mismatch, but indeed calibration mismatch (including pixel-sizes and rotation) also result in gridding..

**Comment by gvarnavi** [comment]
Closing this issue, now that the tutorials have been updated to include [gridding-artifacts](https://github.com/py4dstem/py4DSTEM_tutorials/blob/main/notebooks/ptychography_02.ipynb).
