### ISSUE TITLE
Strain Coordinate System

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#85]
Is there currently a way to calculate the strain in the _uu_ and _vv_ directions (deformation of the lattice vectors) as opposed to the image coordinate strain (the _xx_ and _yy_ strains)?

I suppose you can just take the inverse of the uv_map but this won't give you the shear and rotation (are these rotation invariant?)

**Comment by bsavitzky** [comment]
This is actually a little bit subtle.  The short answer is that there isn't.

The slightly longer answer is that there isn't because trying to do this is
sort of a bad idea.  This is basically because the infinitesimal strain
matrix is defined with respect to an orthonormal coordinate system (for
good reason - trying to define such a transformation for non-orthogonal
coordinates in an unambiguous way seems, from this fool's attempt anyway,
to be a fools errand), and u and v may or may not be orthogonal to one
another.

However, you can (and should!) carefully define the coordinate system of
your strain maps.  First it seems maybe I should clarify that the x/y
directions of the strain maps are *not* the x/y directions of the real
space image.  By default, if you don't do anything to rotate your
coordinate system, they're the x/y directions of diffraction space, as this
is where the reciprocal lattice vectors are calculated.  So for instance,
if you calculated a strain map with

```
strain_map =
get_strain_from_reference_uv(ux_ref,uy_ref,vx_ref,vy_ref,uv_map)
```

then `strain_map.slices['e_xx']` is the element of the infinitessimal
strain matrix oriented along the x-direction of diffraction space.  To
rotate the strain map's coordinate system such that it's oriented along a
direction of your choosing - let's say for argument's sake that you want to
point the x-direction of your strain coordinate system along the direction
of the reference u vector from the line above - you'd use

```
strain_map_uvaxes = get_rotated_strain_map(strain_map, ux_ref, uy_ref)
```

Now, `strain_map_uvaxes.slices['e_xx']` is the element of the
infinitessimal strain matrix oriented along the `(ux_ref, uy_ref)`
direction.  The y-direction of the strain, i.e.
`strain_map_uvaxes.slices['e_yy']`, is set perpendicular to this direction
in a right-handed coordinate system.

Finally, there is the entirely separate question of what direction these
all correspond to in real space!  This requires calibrating the rotational
offset between R/Q space.  Assuming you've done this (see the calibration
module) and have the offset `RQ_offset_angle`, there is a class in the
calibration module called `RQ_axes` for this purpose.  In this example,
you'd use

```
axes = RQ_axes(RQ_offset_angle)
axes.set_Q_axes(ux_ref,uy_ref)
```

The first line instantiates the object, and the second line tells the
object the direction of the axes you're interested in in diffraction space
(again, you specify the x-axis and then a right-handed coordinate system is
assumed).  From here you can grab the real space directions with
`axes.Rux`, `axes.Ruy`, `axes.Rvx`, `axes.Rvy`, and overlay these over any
strain maps you want to show.

If you want the deformation of the lattice vectors u and v and they are
non-orthogonal, then first you'll need to make sure that the undeformed u
and v are what you use for your reference lattice.  Then you can just get
two different rotated strain matrices - e.g., in the example above use

```
strain_map_u = get_rotated_strain_map(strain_map, ux_ref, uy_ref)
strain_map_v = get_rotated_strain_map(strain_map, vx_ref, vy_ref)
```

Now the `e_xx` element of these two objects are `e_uu` and `e_vv`
respectively. This take no computational time, as all we've done is a
matrix rotation.  Importantly, the two strain components *will be different*,
so if that's also a meaningful quantity for your system that you intend to
analyze, you'll have to be careful about that.  Actually, this is one way
of thinking about why we can't just get 'the strain matrix' in uu/vv
coordinates - defining shear would be ambiguous.

Hope this helps!

**Comment by sezelt** [comment]
Yes this makes sense, thanks!
